---
book_repo: pivotal-cf/docs-book-antivirus
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: edge

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
# cross-product resources
- repository:
    name: pivotal-cf/docs-partials
    ref: master
  directory: aws/partials
  no_docs: true

- repository:
    name: pivotal-cf/docs-aws-services
    ref: "1.5"
  directory: aws-services/1-5
  subnav_template: aws-services-subnav-1-5.erb
