---
book_repo: pivotal-cf/docs-book-aws-service-broker
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-aws-services
    ref: 1.4
  directory: aws-services/1-4
  subnav_template: aws-services-subnav.erb