---
book_repo: pivotal-cf/docs-book-aws-service-broker
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master
feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-aws-services
  directory: aws-services
  subnav_template: aws-services-subnav.erb
  